### ISSUE TITLE
draft/preference name

### ISSUE THREAD

**Issue by dret** [inadarei/draft-prefer-transclude#13]
it just dawned on me that terminologically speaking, this draft/preference may be a misnomer. transclusion specifically refers to link resolution being performed on the client side, simply making it look *to the user* as if the transcluded content has been an integral part. what the draft/preference seems to specify is the "opposite": *inclusion* which is performed on the server-side, so that for the client it looks as if the result of the link resolution had been part of the resource from the very beginning. wouldn't it make more sense to call the preference something along the lines of *include* or *resolve* or *follow*?

**Comment by inadarei** [comment]
Hm, language is always tricky, but I am going with this definition:

> In computer science, transclusion is the inclusion of part or all of an electronic document into one or more other documents by hypertext reference. 

from https://en.wikipedia.org/wiki/Transclusion

and I don't see any problem? How critical do you think this issue is?

I don't think the word "transclude" generally has any assumption of whether it is done on client or server, and is about including via a hypertext reference (regardless of who does it), which is what Wikipedia seems to think as well.

**Comment by dret** [comment]
On 2018-01-15 13:28, Irakli Nadareishvili wrote:
> Hm, language is always tricky, but I am going with this definition:
> 
>     In computer science, transclusion is the inclusion of part or all of
>     an electronic document into one or more other documents by hypertext
>     reference.
> 
> from https://en.wikipedia.org/wiki/Transclusion

one of those wikipedia pages that obviously need a little love.

> and I don't see any problem? How critical do you think this issue is?

i may be skewed because i wrote a book on transclusion. but then again 
one could argue that as long as the spec is well-defined, it pretty much 
could be called anything.

i just wanted to raise this early enough so that if considered, the 
rename would not affect already published drafts.

another possible name i came up with was *inline*, which may be a bit 
more fuzzy (in a good way for this scenario) than *include*.

**Comment by inadarei** [comment]
Understood, Erik.

To be perfectly honest - changing the name from transclude to something else, at this late point is a huge deal for me, tho. So unless you think it can cause a major, worldwide disaster, I would kindly ask that we keep the name.

Please? :)

**Comment by dret** [comment]
On 2018-01-15 20:33, Irakli Nadareishvili wrote:
> To be perfectly honest - changing the name from transclude to something 
> else, at this late point is a huge deal for me, tho. So unless you think 
> it can cause a major, worldwide disaster, I would kindly ask that we 
> keep the name.

ok, then. i thought pre-00 might still be a good moment to bring this 
up, but if it already causes breakage in various places, let's just 
soldier on!
